---

- name: application server
  hosts: all
  vars:
    run_scenario: "{{ scenario|default('deploy') }}"

  roles:
    - role: thefinn93.letsencrypt
      letsencrypt_webroot_path: /var/www/html
      letsencrypt_email: user@example.net
      letsencrypt_cert_domains:
        - test.wfx.io
      when: run_scenario == "init"

    - role: roles/docker
      when: run_scenario == "init"

    - role: roles/prepare
      when: run_scenario == "deploy"
      tags:
        - prepare

    - role: roles/nginx
      when: run_scenario == "deploy"

    - role: roles/app
      when: run_scenario == "deploy"
