version: '2'

volumes:
  postgres_data: {}
  postgres_backup: {}
  redis_data: {}
  redis_backup: {}

services:
  postgres:
    image: postgres:9.6
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups

  redis:
    image: redis:4.0
    volumes:
      - redis_data:/var/lib/redis
      - redis_backup:/backups

  web:
    build:
      context: .
      dockerfile: ./compose/web/Dockerfile
      args:
        requirements_file: local.txt
    image: infamily/infinity:dev
    depends_on:
      - postgres
      - redis
    command: ./manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.local
      DJANGO_SECRET_KEY: SECRET
      DATABASE_URL: postgres://postgres@postgres:5432/postgres
      REDIS_URL: redis://redis:6379
      DJANGO_ADMIN_URL: ^admin/
    ports:
      - "8000:8000"
